GET {{host}}/app/rest/investigations?locator=assignee:(username:admin)
Origin: http://localhost:8111
Accept: application/json
Authorization: Basic {{username}} {{password}}

###

GET {{host}}/app/rest/projects/id:_Root/parentProject
Origin: http://localhost:8111
Accept: application/json
Authorization: Basic {{username}} {{password}}

###

GET {{host}}/app/rest/buildTypes/ManyProjects_DeeperProject_1PassingTest1FailingTest_Build1passing1failingWithBranches
Origin: http://localhost:8111
Accept: application/json
Authorization: Basic {{username}} {{password}}

###

GET {{host}}/app/rest/buildTypes/id:ManyProjects_DeeperProject_1PassingTest1FailingTest_Build1passing1failingWithBranches
Origin: http://localhost:8111
Accept: application/json
Authorization: Basic {{username}} {{password}}

###

GET {{host}}/app/rest/projects?fields=project(id,parentProjectId,name,description,href,webUrl)
Origin: http://localhost:8111
Accept: application/json
Authorization: Basic {{username}} {{password}}

###

GET {{host}}/app/rest/investigations/test:(id:5109987273551514521),assignmentProject:(id:ManyProjects_DeeperProject_1PassingTest1FailingTest)?fields=target(tests(test(*)))
Origin: http://localhost:8111
Accept: application/json
Authorization: Basic {{username}} {{password}}

###

GET {{host}}/app/rest/testOccurrences?locator=test:(id:5109987273551514521)&fields=testOccurrence(build(*,defaultBranch))
Origin: http://localhost:8111
Accept: application/json
Authorization: Basic {{username}} {{password}}

###

GET {{host}}/app/rest/testOccurrences?locator=test:(id:7285631191500789829)&fields=testOccurrence(build(*))
Origin: http://localhost:8111
Accept: application/json
Authorization: Basic {{username}} {{password}}

###

GET {{host}}/app/rest/mutes/id:10
Origin: http://localhost:8111
Accept: application/json
Authorization: Basic {{username}} {{password}}
###

problem:(id:10),assignmentProject:(id:ManyProjects_DeeperProject_1PassingTest1FailingTest)


###
GET {{host}}/app/rest/problemOccurrences/problem:(id:13)
Origin: http://localhost:8111
Accept: application/json
Authorization: Basic {{username}} {{password}}

###

GET {{host}}/app/rest/investigations/problem:(id:15)
Origin: http://localhost:8111
Accept: application/json
Authorization: Basic {{username}} {{password}}

###

GET {{host}}/app/rest/tests/id:5109987273551514521
Origin: http://localhost:8111
Accept: application/json
Authorization: Basic {{username}} {{password}}

###

GET {{host}}/app/rest/problems/13?fields=problemOccurrences(*)
Origin: http://localhost:8111
Accept: application/json
Authorization: Basic {{username}} {{password}}

###
# GET BUILDS of build configuration
GET {{host}}/app/rest/buildTypes/id:ManyProjects_DeeperProject_1PassingTest1FailingTest_Build1passing1failingWithBranches
Origin: http://localhost:8111
Accept: application/json
Authorization: Basic {{username}} {{password}}

###

GET {{host}}/app/rest/builds/?locator=buildType:(id:ManyProjects_DeeperProject_1PassingTest1FailingTest_Build1passing1failingWithBranches),branch:(name:refs/heads/second-branch)&fields=build(changes(count))
Origin: http://localhost:8111
Accept: application/json
Authorization: Basic {{username}} {{password}}

###

GET {{host}}/app/rest/changes?locator=build:(id:209)&fields=change(*)
Origin: http://localhost:8111
Accept: application/json
Authorization: Basic {{username}} {{password}}