// flow-typed signature: df8dffff854eb2dc91b5595dc4f9e35b
// flow-typed version: <<STUB>>/@reduxjs/toolkit_v1.4.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@reduxjs/toolkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@reduxjs/toolkit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@reduxjs/toolkit/dist' {
  declare module.exports: any;
}

declare module '@reduxjs/toolkit/dist/redux-toolkit.cjs.development' {
  declare module.exports: any;
}

declare module '@reduxjs/toolkit/dist/redux-toolkit.cjs.production.min' {
  declare module.exports: any;
}

declare module '@reduxjs/toolkit/dist/redux-toolkit.esm' {
  declare module.exports: any;
}

declare module '@reduxjs/toolkit/dist/redux-toolkit.umd' {
  declare module.exports: any;
}

declare module '@reduxjs/toolkit/dist/redux-toolkit.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@reduxjs/toolkit/dist/index' {
  declare module.exports: $Exports<'@reduxjs/toolkit/dist'>;
}
declare module '@reduxjs/toolkit/dist/index.js' {
  declare module.exports: $Exports<'@reduxjs/toolkit/dist'>;
}
declare module '@reduxjs/toolkit/dist/redux-toolkit.cjs.development.js' {
  declare module.exports: $Exports<'@reduxjs/toolkit/dist/redux-toolkit.cjs.development'>;
}
declare module '@reduxjs/toolkit/dist/redux-toolkit.cjs.production.min.js' {
  declare module.exports: $Exports<'@reduxjs/toolkit/dist/redux-toolkit.cjs.production.min'>;
}
declare module '@reduxjs/toolkit/dist/redux-toolkit.esm.js' {
  declare module.exports: $Exports<'@reduxjs/toolkit/dist/redux-toolkit.esm'>;
}
declare module '@reduxjs/toolkit/dist/redux-toolkit.umd.js' {
  declare module.exports: $Exports<'@reduxjs/toolkit/dist/redux-toolkit.umd'>;
}
declare module '@reduxjs/toolkit/dist/redux-toolkit.umd.min.js' {
  declare module.exports: $Exports<'@reduxjs/toolkit/dist/redux-toolkit.umd.min'>;
}
