// flow-typed signature: 2696c1901218772a758dc4b5357bed1d
// flow-typed version: <<STUB>>/just-throttle_v1.1.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'just-throttle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'just-throttle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'just-throttle/index' {
  declare module.exports: $Exports<'just-throttle'>;
}
declare module 'just-throttle/index.js' {
  declare module.exports: $Exports<'just-throttle'>;
}
