// flow-typed signature: 404ce95dba29df91964f7fb43a9fe160
// flow-typed version: <<STUB>>/just-is-empty_v2.0.1/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'just-is-empty'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'just-is-empty' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'just-is-empty/index' {
  declare module.exports: $Exports<'just-is-empty'>;
}
declare module 'just-is-empty/index.js' {
  declare module.exports: $Exports<'just-is-empty'>;
}
