// flow-typed signature: f106c31bb4c92c143b67e1f6865cce12
// flow-typed version: <<STUB>>/just-debounce-it_v1.1.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'just-debounce-it'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'just-debounce-it' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'just-debounce-it/index' {
  declare module.exports: $Exports<'just-debounce-it'>;
}
declare module 'just-debounce-it/index.js' {
  declare module.exports: $Exports<'just-debounce-it'>;
}
