// flow-typed signature: 87b1cd0ca1edb6c147c8d66b4eeaff4c
// flow-typed version: <<STUB>>/react-grid-layout_v1.0.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-grid-layout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-grid-layout' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-grid-layout/__mocks__/react-grid-layout' {
  declare module.exports: any;
}

declare module 'react-grid-layout/build/calculateUtils' {
  declare module.exports: any;
}

declare module 'react-grid-layout/build/components/WidthProvider' {
  declare module.exports: any;
}

declare module 'react-grid-layout/build/fastRGLPropsEqual' {
  declare module.exports: any;
}

declare module 'react-grid-layout/build/GridItem' {
  declare module.exports: any;
}

declare module 'react-grid-layout/build/ReactGridLayout' {
  declare module.exports: any;
}

declare module 'react-grid-layout/build/ReactGridLayoutPropTypes' {
  declare module.exports: any;
}

declare module 'react-grid-layout/build/ResponsiveReactGridLayout' {
  declare module.exports: any;
}

declare module 'react-grid-layout/build/responsiveUtils' {
  declare module.exports: any;
}

declare module 'react-grid-layout/build/utils' {
  declare module.exports: any;
}

declare module 'react-grid-layout/flow-typed/npm/classnames_v2.x.x' {
  declare module.exports: any;
}

declare module 'react-grid-layout/flow-typed/npm/enzyme_v3.x.x' {
  declare module.exports: any;
}

declare module 'react-grid-layout/flow-typed/npm/jest_v24.x.x' {
  declare module.exports: any;
}

declare module 'react-grid-layout/interfaces/classnames' {
  declare module.exports: any;
}

declare module 'react-grid-layout/lib/calculateUtils' {
  declare module.exports: any;
}

declare module 'react-grid-layout/lib/components/WidthProvider' {
  declare module.exports: any;
}

declare module 'react-grid-layout/lib/fastRGLPropsEqual' {
  declare module.exports: any;
}

declare module 'react-grid-layout/lib/GridItem' {
  declare module.exports: any;
}

declare module 'react-grid-layout/lib/ReactGridLayout' {
  declare module.exports: any;
}

declare module 'react-grid-layout/lib/ReactGridLayoutPropTypes' {
  declare module.exports: any;
}

declare module 'react-grid-layout/lib/ResponsiveReactGridLayout' {
  declare module.exports: any;
}

declare module 'react-grid-layout/lib/responsiveUtils' {
  declare module.exports: any;
}

declare module 'react-grid-layout/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-grid-layout/__mocks__/react-grid-layout.js' {
  declare module.exports: $Exports<'react-grid-layout/__mocks__/react-grid-layout'>;
}
declare module 'react-grid-layout/build/calculateUtils.js' {
  declare module.exports: $Exports<'react-grid-layout/build/calculateUtils'>;
}
declare module 'react-grid-layout/build/components/WidthProvider.js' {
  declare module.exports: $Exports<'react-grid-layout/build/components/WidthProvider'>;
}
declare module 'react-grid-layout/build/fastRGLPropsEqual.js' {
  declare module.exports: $Exports<'react-grid-layout/build/fastRGLPropsEqual'>;
}
declare module 'react-grid-layout/build/GridItem.js' {
  declare module.exports: $Exports<'react-grid-layout/build/GridItem'>;
}
declare module 'react-grid-layout/build/ReactGridLayout.js' {
  declare module.exports: $Exports<'react-grid-layout/build/ReactGridLayout'>;
}
declare module 'react-grid-layout/build/ReactGridLayoutPropTypes.js' {
  declare module.exports: $Exports<'react-grid-layout/build/ReactGridLayoutPropTypes'>;
}
declare module 'react-grid-layout/build/ResponsiveReactGridLayout.js' {
  declare module.exports: $Exports<'react-grid-layout/build/ResponsiveReactGridLayout'>;
}
declare module 'react-grid-layout/build/responsiveUtils.js' {
  declare module.exports: $Exports<'react-grid-layout/build/responsiveUtils'>;
}
declare module 'react-grid-layout/build/utils.js' {
  declare module.exports: $Exports<'react-grid-layout/build/utils'>;
}
declare module 'react-grid-layout/flow-typed/npm/classnames_v2.x.x.js' {
  declare module.exports: $Exports<'react-grid-layout/flow-typed/npm/classnames_v2.x.x'>;
}
declare module 'react-grid-layout/flow-typed/npm/enzyme_v3.x.x.js' {
  declare module.exports: $Exports<'react-grid-layout/flow-typed/npm/enzyme_v3.x.x'>;
}
declare module 'react-grid-layout/flow-typed/npm/jest_v24.x.x.js' {
  declare module.exports: $Exports<'react-grid-layout/flow-typed/npm/jest_v24.x.x'>;
}
declare module 'react-grid-layout/index' {
  declare module.exports: $Exports<'react-grid-layout'>;
}
declare module 'react-grid-layout/index.js' {
  declare module.exports: $Exports<'react-grid-layout'>;
}
declare module 'react-grid-layout/interfaces/classnames.js' {
  declare module.exports: $Exports<'react-grid-layout/interfaces/classnames'>;
}
declare module 'react-grid-layout/lib/calculateUtils.js' {
  declare module.exports: $Exports<'react-grid-layout/lib/calculateUtils'>;
}
declare module 'react-grid-layout/lib/components/WidthProvider.jsx' {
  declare module.exports: $Exports<'react-grid-layout/lib/components/WidthProvider'>;
}
declare module 'react-grid-layout/lib/fastRGLPropsEqual.js' {
  declare module.exports: $Exports<'react-grid-layout/lib/fastRGLPropsEqual'>;
}
declare module 'react-grid-layout/lib/GridItem.jsx' {
  declare module.exports: $Exports<'react-grid-layout/lib/GridItem'>;
}
declare module 'react-grid-layout/lib/ReactGridLayout.jsx' {
  declare module.exports: $Exports<'react-grid-layout/lib/ReactGridLayout'>;
}
declare module 'react-grid-layout/lib/ReactGridLayoutPropTypes.js' {
  declare module.exports: $Exports<'react-grid-layout/lib/ReactGridLayoutPropTypes'>;
}
declare module 'react-grid-layout/lib/ResponsiveReactGridLayout.jsx' {
  declare module.exports: $Exports<'react-grid-layout/lib/ResponsiveReactGridLayout'>;
}
declare module 'react-grid-layout/lib/responsiveUtils.js' {
  declare module.exports: $Exports<'react-grid-layout/lib/responsiveUtils'>;
}
declare module 'react-grid-layout/lib/utils.js' {
  declare module.exports: $Exports<'react-grid-layout/lib/utils'>;
}
